# Dependencies
markdown:           kramdown
kramdown:
  math_engine:      mathjax

highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '[tate tian]'
tagline:          'Share thoughts on technology, design and startup'
description:      'I am a computer science Ph.D. candidate and a 
                    full-stack developer who is passionate about <em>building 
                    something useful and fun as well</em>. In this blog, I 
                    share my thoughts on programming, technology and startup.'
url:              http://tatetian.me
baseurl:          /

author:
  name:           'Tate Tian'
  url:            http://tatetian.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tatetian
